config/routes.rb
Rails.application.routes.draw do
  root 'listings#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :listings, only: [:index, :show, :new, :create, :destroy, :update]

  namespace 'api' do
    namespace 'v1' do
      post 'listings/search', to: 'listings#search'
      resources :listings, only: [:index, :create, :show, :destroy, :update]
      resources :amenities, only: [:show, :index, :create]
      resources :pictures, only: [:show, :index, :create]
    end
  end
end

app/models/Picture.rb
class Picture < ApplicationRecord
  belongs_to :listing
end

app/models/amenity.rb
class Amenity < ApplicationRecord
  validates :building_style, presence: true
  validates :parking_spaces, presence: true

  belongs_to :listing
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  validates :bedrooms, presence: true
  validates :bathrooms, presence: true
  validates :rent, presence: true
  validates :date_available, presence: true
  validates :lease_length, presence: true

  belongs_to :listing
end

app/models/image.rb
class Picture < ApplicationRecord
  validates :timestamps, presence: true
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  belongs_to :user
  has_one :amenity
  has_one :feature
  has_many :pictures
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_photo, ProfilePhotoUploader
  has_many :listings

  def admin?
    role == "admin"
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/api/v1/listings_controller.rb
class Api::V1::ListingsController < ApiController

  before_action :authorize_user, except: [:index, :show, :search]

  def index
     render json: Listing.all
  end

  def create
    @listing = Listing.new(location_params)
    @listing.user = current_user
    if @listing.save
      @listing.feature = Feature.new(feature_params)
      @listing.amenity = Amenity.new(amenity_params)
      picture = Picture.new(pictures_params)
      picture.listing = @listing
      picture.save
      render json: { listing: @listing }
    else
      render json: { error: @listing.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    target_id = destroy_listing_params.to_i

    can_delete = (
      !current_user.nil? && (
        current_user == Listing.find(target_id).user ||
        current_user.role == "admin"
      )
    )

    if can_delete
      @listing =Listing.find(target_id)
      if @listing.delete
        render json: { "successful": can_delete }
      else
        render json: { error: @listing.errors.full_messages }, status: :unprocessable_entity
      end
    else
      head 403
    end
  end

  def update
    @listing = Listing.find(params['id'])
      can_edit = (
        !current_user.nil? && (
          current_user == @listing.user ||
          current_user.role == "admin"
        )
      )

    if can_edit
      @listing.update(location_params)
      @listing.feature.update(feature_params)
      @listing.amenity.update(amenity_params)
      @listing.pictures.update(pictures_params)
      if @listing.save
        render json: { listing: @listing }
      else
        render json: { error: @listing.errors.full_messages }, status: :unprocessable_entity
      end
    else
      head 403
    end
  end

  def search
    @listings = Listing.where("street ILIKE ? OR city ILIKE ? OR state ILIKE ? OR zip ILIKE ?", "%#{params['search_string']}%", "%#{params['search_string']}%", "%#{params['search_string']}%", "%#{params['search_string']}%")
    render json: @listings
  end

  def show
    render json: Listing.find(params["id"]), serializer: ListingShowSerializer
  end

  private
  def location_params
    params.permit(:street, :unit, :city, :state, :zip)
  end

  def feature_params
     params.permit(:bedrooms, :bathrooms, :rent, :date_available, :lease_length, :sq_ft, :listing_id)
  end

  def amenity_params
    params.permit(:building_style, :parking_spaces, :pets, :zoning, :school_district, :heating, :cooling, :hud, :smoking)
  end

  def pictures_params
    params.permit(:image)
  end

  def destroy_listing_params
    params.require(:id)
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      flash[:notice] = "You do not have access to this page."
      redirect_to root_path
    end
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :null_session, unless: -> { request.format.json? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protect_from_forgery with: :exception

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_photo, :first_name, :last_name])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

end

app/views/amenities/show.html.erb
<div id="app" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HOM</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV["MAPS_API_KEY"]%>"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body className="background-oh">
  <nav class="top-bar">

    <section class="top-bar-section cursive_light">
      <ul class="left">
        <%- if current_user -%>
        <li><%= link_to 'HOME', root_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to 'NEW LISTING', new_listing_path %></li>
          <% end %>
        <%- else -%>
        <li><%= link_to 'HOME', root_path %></li>
        <%- end -%>
        </ul>

      <ul class="right">
        <%- if current_user -%>
            <li class='profile_name'><%= current_user.first_name %></li>
            <li class='profile_name'><%= current_user.last_name %></li>
            <li class="profile_photo"><img src="<%= current_user.profile_photo %>"  /></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>

        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>
  <div>
    <%= yield %>
  </div>


  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/listings/edit.html.erb
<div id="app" />

app/views/listings/index.html.erb
<div id="app" />

app/views/listings/new.html.erb
<div id="app" />

app/views/listings/show.html.erb
<div id="app" />